### ISSUE TITLE
Cooking/Smelting: cooking time and XP is not displaying (displays translatable instead)

### ISSUE THREAD

**Issue by CamperSamu** [Patbox/polydex#1]
![image](https://user-images.githubusercontent.com/32773961/154652848-efbd0665-1d58-41aa-9498-09747bad0744.png)
![image](https://user-images.githubusercontent.com/32773961/154652862-9ca0d1f4-1d78-4a6f-bd33-fdaace769128.png)

This affects every cooking/smelting block

**Comment by Patbox** [comment]
Ay, I missed these after InteliJ broke all my translations... You can quick fix it for yourself with a datapack containing translations with correct keys. I will fix it in next release
