### ISSUE TITLE
Wrong heart emoji used on entity health

### ISSUE THREAD

**Issue by Minecrafthyr** [Patbox/polydex#12]
Current emoji: ♥(meaning: heart suit, card with heart Emoji)[Link to www.emojiall.com](https://www.emojiall.com/en/emoji/%E2%99%A5)

![image](https://github.com/Patbox/polydex/assets/107340726/642d65b4-0156-41c4-af52-c79790b31cf9)

Correct emoji: ❤(meaning: red heart, love heart Emoji)[Link to www.emojiall.com](https://www.emojiall.com/en/emoji/%E2%9D%A4)

![image](https://github.com/Patbox/polydex/assets/107340726/3e85dc71-d384-4421-87e2-853587e888dd)

**Comment by Patbox** [comment]
Thats one of a nitpick thats for sure, but will look into that maybe lol
