### ISSUE TITLE
Incompatability with Trinkets

### ISSUE THREAD

**Issue by LottieVixen** [Patbox/polydex#5]
Incompatible with mods using [Trinkets](https://github.com/emilyploszaj/trinkets) and I'm not sure why as their were no obvious warnings, 

Discovered with [Scout](https://github.com/Cynosphere-mc/Scout) for some reason it removed trinket slots.

**Comment by LottieVixen** [comment]
Mentioned on the Trinkets repo, emilyploszaj/trinkets#198

**Comment by Patbox** [comment]
Any logs/errors?

**Comment by LottieVixen** [comment]
log here, had stuff equipped in trinket slots, loaded a world, the dropped at my feet then popped into my inventory.

[latest.log](https://github.com/Patbox/polydex/files/9275949/latest.log)

**Comment by Patbox** [comment]
Ah I know whats broken then.  Install https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.12%2B1.18.2/server-translations-api-1.4.12%2B1.18.2.jar and it should work
